POST http://localhost:3000/api/status HTTP/1.1


###
POST http://localhost:3000/api/videos HTTP/1.1
Content-Type: application/json

{"page":"1","channel":"alice","sort":"popular","sexuality":"straight"}

###
POST http://localhost:3000/api/search HTTP/1.1
Content-Type: application/json

{"page":"1","channel":"alice","sort":"popular","sexuality":"straight","query":"test"}

###
POST http://54.188.220.83:3000/api/status HTTP/1.1
