export const CHANNELS = [
  {
    id: "hottub",
    name: "Hot Tub Pro",
    premium: true,
    favicon: "https://www.google.com/s2/favicons?sz=64&domain=https://hottubapp.io",
    status: "active",
    categories: [
      "Teen",
      "Amateur",
      "Public",
      "Babe",
      "Compilation",
      "Vintage",
      "Reality",
      "Massage",
      "Red Head",
      "POV",
    ],
    options: [
      {
        id: "sort",
        title: "Sort",
        systemImage: "list.number",
        colorName: "indigo",
        options: [
          { id: "relevance", title: "Most Relevant" },
          { id: "recent", title: "Newest" },
          { id: "rating", title: "Top Rated" },
          { id: "views", title: "Most Viewed" },
          { id: "duration", title: "Longest" },
        ],
      },
      {
        id: "duration",
        title: "Duration",
        systemImage: "timer",
        colorName: "green",
        multiSelect: false,
        options: [
          { id: "any", title: "Any" },
          { id: "short", title: "Short (<10 min)" },
          { id: "medium", title: "Medium (10-30 min)" },
          { id: "long", title: "Long (>30 min)" },
        ],
      },
      {
        id: "production",
        title: "Production Type",
        systemImage: "film",
        colorName: "blue",
        options: [
          { id: "any", title: "Any" },
          { id: "homemade", title: "Homemade" },
          { id: "professional", title: "Professional" },
        ],
      },
      {
        id: "verified",
        title: "Verified",
        systemImage: "checkmark.seal.fill",
        colorName: "blue",
        options: [
          { id: "any", title: "Any" },
          { id: "verified", title: "Verified" },
        ],
      },
    ],
  },
  {
    id: "xvideos",
    name: "XVideos",
    favicon: "https://www.google.com/s2/favicons?sz=64&domain=xvideos.com",
    description: "The best free porn videos on internet.",
    status: "active",
    options: [
      {
        id: "sort",
        title: "Sort",
        systemImage: "list.number",
        colorName: "indigo",
        options: [
          { id: "relevance", title: "Most Relevant" },
          { id: "new", title: "Newest" },
          { id: "rating", title: "Top Rated" },
          { id: "duration", title: "Longest" },
          { id: "views", title: "Most Viewed" },
          { id: "random", title: "Random" },
        ],
      },
    ],
    categories: [
      "Teen",
      "Amateur",
      "Public",
      "Babe",
      "Compilation",
      "Vintage",
      "Reality",
      "Massage",
      "Red Head",
      "POV",
    ],
  },
  {
    id: "pornhub",
    name: "PornHub",
    description: "Home of the best hardcore free porn videos with the hottest adult stars.",
    favicon: "https://www.google.com/s2/favicons?sz=64&domain=pornhub.com",
    status: "active",
    options: [
      {
        id: "sort",
        title: "Sort",
        systemImage: "list.number",
        colorName: "indigo",
        options: [
          { id: "relevance", title: "Most Relevant" },
          { id: "recent", title: "Newest" },
          { id: "rating", title: "Top Rated" },
          { id: "views", title: "Most Viewed" },
          { id: "longest", title: "Longest" },
        ],
      },
    ],
    categories: [
      "Teen",
      "Amateur",
      "Public",
      "Babe",
      "Compilation",
      "Vintage",
      "Reality",
      "Massage",
      "Red Head",
      "POV",
    ],
  },
  {
    id: "xnxx",
    name: "XNXX",
    favicon: "https://www.google.com/s2/favicons?sz=64&domain=xnxx.com",
    description: "XNXX delivers free sex movies and fast free porn videos (tube porn).",
    status: "active",
    options: [
      {
        id: "sort",
        title: "Sort",
        systemImage: "list.number",
        colorName: "indigo",
        options: [
          { id: "relevance", title: "Most Relevant" },
          { id: "recent", title: "Newest" },
          { id: "rating", title: "Top Rated" },
          { id: "views", title: "Most Viewed" },
          { id: "trending", title: "Trending" },
          { id: "duration", title: "Longest" },
        ],
      },
    ],
    categories: [
      "Teen",
      "Amateur",
      "Public",
      "Babe",
      "Compilation",
      "Vintage",
      "Reality",
      "Massage",
      "Red Head",
      "POV",
    ],
  },
  {
    id: "eporner",
    name: "Eporner",
    favicon: "https://www.google.com/s2/favicons?sz=64&domain=eporner.com",
    description: "Watch Full HD Porn Videos for free.",
    status: "active",
    options: [
      {
        id: "sort",
        title: "Sort",
        systemImage: "list.number",
        colorName: "indigo",
        options: [
          { id: "popular", title: "Popular" },
          { id: "latest", title: "Latest" },
          { id: "longest", title: "Longest" },
          { id: "shortest", title: "Shortest" },
          { id: "top-rated", title: "Top Rated" },
          { id: "top-weekly", title: "Top Weekly" },
          { id: "top-monthly", title: "Top Monthly" },
        ],
      },
    ],
    categories: [
      "Teen",
      "Amateur",
      "Public",
      "Babe",
      "Compilation",
      "Vintage",
      "Reality",
      "Massage",
      "Red Head",
      "POV",
    ],
  },
  {
    id: "pussy-play",
    name: "Pussy Play",
    premium: false,
    favicon: "http://cdn-icons-png.flaticon.com/512/616/616430.png",
    status: "active",
    categories: ["Funny Cats", "Kittens", "Cat Fails", "Fluffy Cats", "Cute Cats", "Cats and Dogs"],
    categoryMap: {},
    options: [
      {
        id: "sort",
        title: "Sort",
        systemImage: "list.number",
        colorName: "indigo",
        options: [
          { id: "relevance", title: "Most Relevant" },
          { id: "recent", title: "Latest" },
          { id: "rating", title: "Top Rated" },
          { id: "views", title: "Most Popular" },
          { id: "duration", title: "Longest" },
          { id: "trending", title: "Trending Now" },
        ],
      },
      {
        id: "duration",
        title: "Duration",
        systemImage: "timer",
        colorName: "green",
        options: [
          { id: "short", title: "Short (<10 min)" },
          { id: "medium", title: "Medium (10-30 min)" },
          { id: "long", title: "Long (>30 min)" },
        ],
      },
      {
        id: "production",
        title: "Production Type",
        systemImage: "film",
        colorName: "blue",
        options: [
          { id: "all", title: "All Content" },
          { id: "homemade", title: "Amateur" },
          { id: "professional", title: "Studio" },
          { id: "model", title: "Premium Models" },
        ],
      },
    ],
  },
];

export const channels = (req, res) => {
  res.json({ channels: CHANNELS });
};
